# Відповідність місць на сайті → 3D-іконки Microsoft Fluent Emoji (MIT).
# "@Name" — людина (береться світлий тон шкіри).
# Для тем: [головна, допоміжна1, допоміжна2].

TOPICS = {
    # Казки
    "pryntsesy": ["@Princess", "Crown", "Castle"],
    "lytsari": ["Dragon", "Shield", "Crossed swords"],
    "charivnyi-lis": ["Deciduous tree", "Owl", "Mushroom"],
    "fei": ["@Person fairy", "Sparkles", "Blossom"],
    "yedynorohy": ["Unicorn", "Rainbow", "Sparkles"],
    "rusalky": ["@Person merpeople", "Spiral shell", "Tropical fish"],
    "veletni": ["Ogre", "Hiking boot", "House"],
    "hnomy": ["Goblin", "Mushroom", "Hammer"],
    "charivna-shkola": ["@Person mage", "Magic wand", "Books"],
    "chariviyky": ["Magic wand", "Crystal ball", "Black cat"],
    "kazka-na-nich": ["Crescent moon", "Star", "Teddy bear"],
    # Пригоди
    "smittievoz": ["Delivery truck", "Wastebasket", "Recycling symbol"],
    "budivelna-tekhnika": ["Building construction", "Construction", "Hammer and wrench"],
    "litak": ["Airplane", "Cloud", "Sun"],
    "perehony": ["Racing car", "Chequered flag", "Trophy"],
    "pozhezhnyky": ["Fire engine", "@Firefighter", "Fire"],
    "politsiia": ["Police car", "@Police officer", "Magnifying glass tilted left"],
    "dynozavry": ["T-rex", "Sauropod", "Egg"],
    "piraty": ["Sailboat", "Parrot", "Skull and crossbones"],
    "superheroi": ["@Person superhero", "High voltage", "Star"],
    "kempinh": ["Camping", "Tent", "Fire"],
    "podorozhi": ["Luggage", "Globe showing europe-africa", "Airplane"],
    "skarb": ["World map", "Coin", "Gem stone"],
    "taiemna-misiia": ["@Detective", "Magnifying glass tilted right", "Key"],
    "budynok-pryvydiv": ["Derelict house", "Ghost", "Candle"],
    "podorozh-u-chasi": ["Hourglass not done", "Mantelpiece clock", "Sparkles"],
    # Заняття
    "sport": ["Soccer ball", "Sports medal", "Trophy"],
    "tantsi": ["Ballet shoes", "Musical notes", "Sparkles"],
    "muzyka": ["Drum", "Trumpet", "Musical notes"],
    "maliuvannia": ["Artist palette", "Paintbrush", "Crayon"],
    "kukhnia": ["Cooking", "Birthday cake", "Cookie"],
    "sadivnytstvo": ["Potted plant", "Seedling", "Sunflower"],
    "zoopark": ["Giraffe", "Elephant", "Lion"],
    "park-rozvah": ["Ferris wheel", "Roller coaster", "Carousel horse"],
    "tsyrk": ["Circus tent", "Clown face", "Admission tickets"],
    "biblioteka": ["Books", "Open book", "Bookmark"],
    "likar": ["Stethoscope", "Teddy bear", "Adhesive bandage"],
    "stomatoloh": ["Tooth", "Toothbrush", "Sparkles"],
    "budynochok-na-derevi": ["Deciduous tree", "Ladder", "House"],
    "hry-nadvori": ["Kite", "Playground slide", "Soccer ball"],
    "potiah": ["Locomotive", "Railway car", "Railway track"],
    "perevdiahannia": ["Top hat", "Performing arts", "Womans hat"],
    "pliazh": ["Beach with umbrella", "Spiral shell", "Bucket"],
    "ferma": ["Cow", "Tractor", "Baby chick"],
    "turbota-tvaryny": ["Dog", "Cat", "Paw prints"],
    "tvorchist": ["Scissors", "Crayon", "Yarn"],
    # Світи
    "kosmos": ["Rocket", "Ringed planet", "Star"],
    "dzhunhli": ["Monkey", "Palm tree", "Parrot"],
    "savana": ["Lion", "Giraffe", "Zebra"],
    "pivnichnyi-polius": ["Polar bear", "Penguin", "Snowflake"],
    "pidvodnyi-svit": ["Turtle", "Tropical fish", "Coral"],
    "kraina-solodoshchiv": ["Lollipop", "Candy", "Cupcake"],
    "dykyi-zakhid": ["Horse", "Cactus", "Cowboy hat face"],
    "yehypet": ["Camel", "Desert", "Scroll"],
    "hretsiia": ["Classical building", "Amphora", "Olive"],
    "kamianyi-vik": ["Mammoth", "Rock", "Fire"],
    "vikinhy": ["Sailboat", "Shield", "Axe"],
    "seredniovichchia": ["Castle", "Shield", "Horse"],
    "maibutnie": ["Robot", "Flying saucer", "Satellite"],
    "tysiacha-nochei": ["Magic wand", "Crescent moon", "Man genie"],
    "kozatska-sich": ["Horse", "Crossed swords", "Water wave"],
    "ukrainske-selo": ["Sunflower", "Rooster", "House with garden"],
    # Свята
    "den-narodzhennia": ["Birthday cake", "Balloon", "Wrapped gift"],
    "mykolai": ["Wrapped gift", "Snowflake", "Candy"],
    "rizdvo": ["Christmas tree", "Star", "Wrapped gift"],
    "novyi-rik": ["Fireworks", "Party popper", "Mantelpiece clock"],
    "velykden": ["Egg", "Basket", "Tulip"],
    "den-materi": ["Tulip", "Bouquet", "Heart with ribbon"],
    "den-batka": ["Toolbox", "Necktie", "Trophy"],
    "den-ditei": ["Balloon", "Kite", "Sparkles"],
    "den-babusi-didusia": ["@Old woman", "@Old man", "Pie"],
    "imenyny": ["Wrapped gift", "Name badge", "Confetti ball"],
    "pershyi-dzvonyk": ["Backpack", "Bell", "Bouquet"],
    "vypusknyi": ["Graduation cap", "Teddy bear", "Balloon"],
    "kupala": ["Blossom", "Fire", "Water wave"],
    "valentyn": ["Heart with ribbon", "Love letter", "Rose"],
    "helovin": ["Jack-o-lantern", "Ghost", "Candy"],
    "karnaval": ["Performing arts", "Confetti ball", "Party popper"],
    "den-nezalezhnosti": ["Sunflower", "Sheaf of rice", "Sparkles"],
    "den-vyshyvanky": ["Thread", "Sewing needle", "Blossom"],
    # Родина
    "bratyk": ["@Baby", "Baby bottle", "Teddy bear"],
    "sestrychka": ["@Baby", "Baby bottle", "Ribbon"],
    "maliatko": ["@Baby", "Baby symbol", "Star"],
    "uliublenets": ["Dog", "Paw prints", "Bone"],
    "pereizd": ["Package", "House", "Delivery truck"],
    "vesillia": ["Ring", "Wedding", "Bouquet"],
    "nochivlia": ["Tent", "Flashlight", "Teddy bear"],
    "vidpustka": ["Luggage", "Beach with umbrella", "Sunglasses"],
    "babusia-didus": ["House with garden", "Pie", "Honey pot"],
    "rozluchennia": ["House", "Rainbow", "Two hearts"],
    "zmishana-rodyna": ["Houses", "Two hearts", "Deciduous tree"],
    "proshchannia": ["Glowing star", "Balloon", "Two hearts"],
    # Навчальні
    "abetka": ["Input latin uppercase", "Pencil", "Open book"],
    "lichba": ["Abacus", "Input numbers", "Pencil"],
    "pershi-slova": ["Speech balloon", "Baby bottle", "Teddy bear"],
    "kolory-formy": ["Artist palette", "Large orange diamond", "Crayon"],
    "pory-roku": ["Sun behind rain cloud", "Snowflake", "Fallen leaf"],
    "chastyny-tila": ["Teddy bear", "Ear", "Nose"],
    "horshchyk": ["Toilet", "Star", "Roll of paper"],
    "pustushka": ["Baby bottle", "Waving hand", "Star"],
    "chyshchennia-zubiv": ["Toothbrush", "Tooth", "Bubbles"],
    "velosyped": ["Bicycle", "Sports medal", "Sparkles"],
    "shnurky": ["Running shoe", "Ribbon", "Sparkles"],
    "hodynnyk": ["Alarm clock", "Mantelpiece clock", "Hourglass done"],
    "prybyrannia": ["Broom", "Basket", "Teddy bear"],
    "kyshenkovi": ["Pig face", "Coin", "Money bag"],
    "kharchuvannia": ["Carrot", "Broccoli", "Red apple"],
    "pershi-kroky": ["@Baby", "Footprints", "Star"],
    "palchyk": ["Thumbs up", "Star", "Sparkles"],
    # Почуття
    "strakh-temriavy": ["Crescent moon", "Flashlight", "Teddy bear"],
    "sorom-iazlyvist": ["Turtle", "Blossom", "Sparkles"],
    "hniv": ["Cloud with lightning", "Sun behind cloud", "Wind face"],
    "revnoshchi": ["Teddy bear", "Two hearts", "Revolving hearts"],
    "tuha": ["House", "Snowflake", "Heart with ribbon"],
    "vpevnenist": ["Trophy", "Star", "Flexed biceps"],
    "buling": ["Handshake", "Shield", "Two hearts"],
    "vplyv-druziv": ["Compass", "Two hearts", "Footprints"],
    "nevpevnenist": ["Bird", "Feather", "Sparkles"],
    "emotsii": ["Rainbow", "Beaming face with smiling eyes", "Cloud"],
    "hordist": ["Sports medal", "Star-struck", "Trophy"],
    # Історії
    "mriia": ["Cloud", "Crescent moon", "Star"],
    "smishni": ["Rolling on the floor laughing", "Confetti ball", "Clown face"],
}

CATEGORIES = {
    "kazky": "Castle",
    "pryhody": "World map",
    "zaniattia": "Artist palette",
    "svity": "Globe showing europe-africa",
    "sviata": "Wrapped gift",
    "rodyna": "House with garden",
    "navchalni": "Abacus",
    "pochuttia": "Two hearts",
    "istorii": "Books",
}

MORALS = {
    "druzhba": "Handshake",
    "smilyvist": "Lion",
    "pryroda": "Seedling",
    "liubov": "Heart with ribbon",
    "napolehlyvist": "Snail",
    "dilytysia": "Cookie",
    "chesnist": "Glowing star",
    "povaha": "Folded hands",
}

AGE_GROUPS = {"0-2": "@Baby", "3-5": "@Child", "6-9": "@Student", "10+": "@Person"}

# Вік (/vik): [головна, допоміжна]
AGE_PAGES = {
    "nemovlia": ["@Baby", "Baby bottle"],
    "1-rik": ["@Baby", "Birthday cake"],
    "2-roky": ["@Child", "Teddy bear"],
    "3-roky": ["@Child", "Balloon"],
    "4-roky": ["@Child", "Kite"],
    "5-rokiv": ["@Child", "Input latin uppercase"],
    "6-rokiv": ["@Student", "Backpack"],
    "7-rokiv": ["@Student", "Books"],
    "8-rokiv": ["@Student", "Soccer ball"],
    "9-rokiv": ["@Student", "Headphone"],
    "10-rokiv": ["@Person", "Open book"],
    "11-rokiv": ["@Person", "Skateboard"],
    "12-rokiv": ["@Person", "Video game"],
    "13-rokiv": ["@Person", "Guitar"],
    "14-rokiv": ["@Person", "Laptop"],
    "15-rokiv": ["@Person", "Graduation cap"],
}

GIFTS = {
    "mykolai": ["Wrapped gift", "Snowflake", "Candy"],
    "rizdvo": ["Christmas tree", "Wrapped gift", "Star"],
    "den-narodzhennia": ["Birthday cake", "Balloon", "Wrapped gift"],
    "narodzhennia-dytyny": ["@Baby", "Baby bottle", "Star"],
    "imenyny": ["Wrapped gift", "Name badge", "Confetti ball"],
    "valentyn": ["Heart with ribbon", "Love letter", "Rose"],
    "velykden": ["Egg", "Basket", "Tulip"],
    "den-materi": ["Bouquet", "Tulip", "Heart with ribbon"],
    "den-ditei": ["Kite", "Balloon", "Sparkles"],
    "den-batka": ["Toolbox", "Necktie", "Trophy"],
    "litni-kanikuly": ["Beach with umbrella", "Luggage", "Sun"],
    "do-shkoly": ["Backpack", "Bell", "Books"],
    "starshyi-brat-sestra": ["@Baby", "Crown", "Two hearts"],
}

EXTRAS = {
    "lystivka": ["Envelope", "Love letter", "Sparkles"],
    "rozmalovka": ["Crayon", "Open book", "Artist palette"],
    "polotno": ["Framed picture", "Paintbrush", "Sparkles"],
    "kalendar": ["Spiral calendar", "Birthday cake", "Star"],
}

FEATURES = {
    "temy": ["Books", "Rocket", "T-rex"],
    "heroi": ["@Child", "Dog", "Teddy bear"],
    "uliublenets": ["Dog", "Teddy bear", "Paw prints"],
    "vik": ["@Baby", "@Child", "@Student"],
    "styli": ["Artist palette", "Paintbrush", "Framed picture"],
    "shryft": ["Input latin uppercase", "Black nib", "Pencil"],
    "peredmova": ["Love letter", "Fountain pen", "Heart with ribbon"],
    "redahuvannia": ["Pencil", "Magic wand", "Open book"],
    "prodovzhennia": ["Books", "Sparkles", "Glowing star"],
    "rozmalovka": ["Crayon", "Artist palette", "Open book"],
}

HOME = {
    "krok-1": ["@Child", "Camera with flash", "Sparkles"],
    "krok-2": ["Open book", "Artist palette", "Castle"],
    "krok-3": ["Books", "Heart with ribbon", "Sparkles"],
    "podarunok": ["Wrapped gift", "Open book", "Confetti ball"],
}
