// Можливості персоналізації (/mozhlyvosti) — у тому ж порядку, що на зразку.
export type Feature = { id: string; title: string; text: string; link: string; href: string; isNew?: boolean; image: string };

export const FEATURES: Feature[] = [
  {
    id: "temy",
    title: "Захопливі теми історій",
    text: "Обирайте з понад сотні тем: від пригод і казкових мандрівок до повчальних історій про дружбу й природу. Тема, яка зачепить саме вашу дитину, точно знайдеться.",
    link: "Оберіть тему історії",
    href: "/temy",
    image: "an open storybook with a castle, a rocket, a dinosaur and a pirate ship popping out of its pages",
  },
  {
    id: "heroi",
    title: "П'ять героїв в одній історії",
    text: "Створіть багату й живу історію, додавши до п'яти різних персонажів. Дайте роль друзям, рідним чи вигаданим героям!",
    link: "Додайте героїв до історії",
    href: "/stvoryty",
    image: "five cute storybook characters standing together: a girl, a boy, a grandma, a puppy and a teddy bear",
  },
  {
    id: "uliublenets",
    title: "Улюбленець і плюшевий друг у пригоді",
    text: "Песик — справжній герой, а без улюбленого ведмедика ніяк? Дайте їм головну роль в історії — і книжка стане ще особливішою.",
    link: "Дайте роль улюбленцю",
    href: "/stvoryty",
    image: "a happy puppy and a plush teddy bear wearing tiny adventure backpacks",
  },
  {
    id: "vik",
    title: "Під кожен вік",
    text: "Наші історії ростуть разом із дитиною. Ми підлаштовуємо складність слів, довжину речень і будову сюжету під обраний вік — щоб читати було і цікаво, і зрозуміло.",
    link: "Переглянути вікові групи",
    href: "/vik",
    image: "four books of different sizes from a baby board book to a thick novel standing in a row like a growth chart",
  },
  {
    id: "styli",
    title: "Неповторні стилі ілюстрацій",
    text: "Десять стилів ілюстрацій на вибір. Ніжна акварель чи жива глибина 3D-анімації? Кожна книжка стане святом для очей.",
    link: "Усі стилі ілюстрацій",
    href: "/stvoryty",
    image: "a fan of illustration swatches showing the same child in watercolour, 3D, comic, clay and paper collage styles",
  },
  {
    id: "shryft",
    title: "Оберіть власний шрифт",
    text: "Зробіть історію ще особистішою, обравши шрифт, що пасує до настрою й зручний для читання вашій дитині. Від грайливого до класичного — вибір за вами.",
    link: "Оберіть улюблений шрифт",
    href: "/stvoryty",
    image: "colourful wooden letter blocks in different playful typefaces",
  },
  {
    id: "peredmova",
    title: "Додайте особисту передмову",
    text: "Зробіть книжку неповторною завдяки особистому зверненню. Напишіть теплу передмову спеціально для маленького читача — і історія почнеться з любові.",
    link: "Напишіть передмову",
    href: "/stvoryty",
    image: "a handwritten letter with a heart tucked inside the first page of a hardcover picture book",
  },
  {
    id: "redahuvannia",
    title: "Легко змінюйте тексти й ілюстрації",
    text: "Щось не так? Не біда! Після створення всі тексти можна відредагувати на свій смак, а ілюстрацію, що не сподобалась, легко замінити.",
    link: "Персоналізуйте книжку повністю",
    href: "/stvoryty",
    image: "an open book on a tablet with a pencil editing a page and a magic wand swapping an illustration",
  },
  {
    id: "prodovzhennia",
    title: "Продовження з тими самими героями",
    text: "Перша пригода позаду? Створіть продовження! Ваші герої й стиль ілюстрацій автоматично повернуться в новій історії. Складіть власну книжкову серію, що росте разом із дитиною.",
    link: "Почніть власну серію",
    href: "/moi-kazky",
    isNew: true,
    image: "three matching hardcover picture books of a series standing together with numbers 1, 2, 3 made of stars",
  },
  {
    id: "rozmalovka",
    title: "Ілюстрації з книжки — у розмальовку",
    text: "Додайте творчості! Одним натисканням ілюстрації з вашої книжки стають гарною розмальовкою. Ідеально, щоб розфарбовувати разом і знову переживати історію.",
    link: "Спробуйте розмальовку",
    href: "/moi-kazky",
    isNew: true,
    image: "an illustrated storybook page next to the same page as a black-and-white colouring outline with crayons",
  },
];
